# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        review:
            persistence:
                driver: orm
                model: App\Entity\Review
                provider: ~
                finder: ~
            properties:
                name: ~
                text: ~
                comments:
                    type: nested
                    properties:
                        text: ~
